---

# handling nginx 

# restart nginx as asked in tasks
- name: restart nginx
  service: name=nginx state=restarted enabled=yes
  nginx: nginx_restart
#reload nginx as asked in tasks
- name: reload nginx
  service: name=nginx state=reloaded
  tags: nginx_reload

# check whether nginx configuration is working good
- name: validate nginx configuration
  command: "nginx -t -c /etc/nginx/nginx.conf"
  register: nginx_configuration
  tags: nginx_configuration
